services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "81:80"
        depends_on:
            - app
        container_name: testingService-nginx

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - db
        container_name: testingService-app


    db:
        image: mysql:8.4.0
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: testingServ_db
            MYSQL_USER: testingAdmU
            MYSQL_PASSWORD: testAdmP@ss
            MYSQL_ROOT_PASSWORD: testRootP@ss
        ports:
            - "3360:3306"
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: testingService-db


    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
            PMA_USER: testingAdmU
            PMA_PASSWORD: testAdmP@ss
        depends_on:
            - db

